on: 
  release:
    types: [created]

jobs:
   release:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.18]
    name: Release
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.28
      with:
        github_token: ${{ secrets.TOKEN }}
        pre_command: go get -u
        goversion: "https://dl.google.com/go/go1.18.linux-amd64.tar.gz"
        binary_name: "plank"
        extra_files: LICENSE README.md
