name: Swift

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.4"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: fwal/setup-swift@d43a564349d1341cd990cfbd70d94d63b8899475
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v2
      - name: Update Packages
        run: swift package update
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
      - name: Build Debug
        run: swift build -c debug
      - name: Build Release
        run: swift build -c release
      - name: Create Holder Folder
        run: |
          mkdir temp/
          cp .build/debug/plank temp/plank-debug
          cp .build/release/plank temp/plank
          zip -r Artifacts.zip temp/*
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Bin
          path: |
            Artifacts.zip
            
        
