name: Build and test with Swift on Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  swift_for_windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - uses: MaxDesiatov/swift-windows-action@v1
